<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bharath" failures="1" tests="6" name="com.framework.testng.concepts.AppCommons" time="0.025" errors="0" timestamp="2025-02-17T21:57:08 IST" skipped="2">
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase2" time="0.005"/>
  <system-out/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.001">
    <failure message="Test Case 1 Failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test Case 1 Failed
at org.testng.Assert.fail(Assert.java:99)
at com.framework.testng.concepts.AppCommons.TestCase1(AppCommons.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TestCase1 -->
  <system-out/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.009">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <system-out/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase1" time="0.002">
    <skipped/>
  </testcase> <!-- TestCase1 -->
  <system-out/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase3" time="0.003"/>
  <system-out/>
  <testcase classname="com.framework.testng.concepts.AppCommons" name="TestCase3" time="0.005"/>
  <system-out/>
</testsuite> <!-- com.framework.testng.concepts.AppCommons -->
